const ROUTES = {
  home:"/",
  address:"/address",
  products:"/products",
  about:"/about",
  homeVerification:"/verification",
  corporate:'/corporate',
  organisation:'/corporate',
  register: '/auth/signup',
  login: '/auth/login',
  passwordReset:'/auth/reset-password',
  dashboard: '/dashboard',
  kyc: '/dashboard/user/kyc',
  claim: '/dashboard/user/claim',
  addAddress: '/dashboard/user/claim/addressForm',
  claimedAddress: '/dashboard/user/claim/claimAddress',
  completeClaim :'/dashboard/user/claim/2',
  verifiedAddress: '/dashboard/user/claim/verify',
  viewAddress: '/dashboard/user/claim/map',
  shareAddress: '/dashboard/user/share',
  userSettings: '/dashboard/user/settings',
  transactions: '/dashboard/transactions',
  purchases: '/dashboard/purchases',
  withdrawals: '/dashboard/withdrawals',
  map: '/dashboard/map',
  addresses: '/dashboard/addresses',
  verification: '/dashboard/verification',
  verificationRequest: '/dashboard/verification/request',
  emergencies: '/dashboard/emergencies',
  emergencyRequest: '/dashboard/emergencies/request',
  emergencyDepartment: '/dashboard/emergencies/department',
  people: '/dashboard/people',
  activities: '/dashboard/activities',
  settings: '/dashboard/settings',
};

export default ROUTES;
